name: Deploy Maven artifact

on:
  workflow_call:
    inputs:
      directory:
        type: string
    secrets:
      token:
        required: true

jobs:
  deploy:
    name: Deploy artifact to GitHub Packages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
          cache: maven
      - name: Check SNAPSHOT state
        run: |
          echo "debug1"
          if [[ -n "${{ inputs.directory }}" ]]; then
            echo "debug2"
            cd "${{ inputs.directory }}"
          fi

          echo "debug3"
          branch=${GITHUB_REF##*/}
          echo "$branch"
          mvn help:evaluate -Dexpression=project.version
          version=$(mvn help:evaluate -Dexpression=project.version -DforceStdout)
          echo "$version"

          if [[ "$branch" == "master" ]] || [[ "$branch" == "main" ]]; then
            echo "On branch '${branch}', keeping version '${version}' as is."
          elif [[ "$version" == *SNAPSHOT ]]; then
            echo "On branch '${branch}', version '${version}' is already a SNAPSHOT version."
          else
            echo "On branch '${branch}', appending -SNAPSHOT to version '${version}'."
            mvn versions:set versions:commit -DnewVersion="${version}-SNAPSHOT" -q
          fi
        env:
          GITHUB_TOKEN: "${{ secrets.token }}"
      - name: Publish artifact
        run: |
          if [[ -n "${{ inputs.directory }}" ]]; then
            cd "${{ inputs.directory }}"
          fi

          mvn -B clean deploy
        env:
          GITHUB_TOKEN: "${{ secrets.token }}"
