name: Deploy Maven artifact

on:
  workflow_call:
    inputs:
      directory:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  deploy:
    name: Deploy artifact to GitHub Packages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
          cache: maven
      - name: Check SNAPSHOT state
        run: |
          branch=${GITHUB_REF##*/}
          version=$(mvn help:evaluate -Dexpression=project.version -DforceStdout -q)
          if [[ "$branch" != "master" ]] && [[ "$branch" != "main" ]] && [[ "$version" != *SNAPSHOT ]]; then
            echo "Appending -SNAPSHOT to artifact version because not on main branch"
            mvn versions:set versions:commit -DnewVersion="${version}-SNAPSHOT" -q
          fi
        working-directory: ${{ inputs.directory }}
      - name: Publish artifact
        run: mvn -B clean deploy
        working-directory: ${{ inputs.directory }}
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
